/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteRouteImport } from './routes/upload/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UploadTokenRouteImport } from './routes/upload/$token'

const UploadRouteRoute = UploadRouteRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadTokenRoute = UploadTokenRouteImport.update({
  id: '/$token',
  path: '/$token',
  getParentRoute: () => UploadRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upload': typeof UploadRouteRouteWithChildren
  '/upload/$token': typeof UploadTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upload': typeof UploadRouteRouteWithChildren
  '/upload/$token': typeof UploadTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/upload': typeof UploadRouteRouteWithChildren
  '/upload/$token': typeof UploadTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/upload' | '/upload/$token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/upload' | '/upload/$token'
  id: '__root__' | '/' | '/upload' | '/upload/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UploadRouteRoute: typeof UploadRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$token': {
      id: '/upload/$token'
      path: '/$token'
      fullPath: '/upload/$token'
      preLoaderRoute: typeof UploadTokenRouteImport
      parentRoute: typeof UploadRouteRoute
    }
  }
}

interface UploadRouteRouteChildren {
  UploadTokenRoute: typeof UploadTokenRoute
}

const UploadRouteRouteChildren: UploadRouteRouteChildren = {
  UploadTokenRoute: UploadTokenRoute,
}

const UploadRouteRouteWithChildren = UploadRouteRoute._addFileChildren(
  UploadRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UploadRouteRoute: UploadRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
